name: Build FitnessApp.SettingsApi image

on:
  push:
    branches:
    - master
    - develop

env:
  API_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/fitness-app-settings-api

jobs:
  build:
    runs-on: ubuntu-latest
    outputs: 
      Version: ${{ steps.gitversion.outputs.SemVer }}
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}
    
    services:
      mongo-db:
        image: mongo
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'db.runCommand("ping").ok' | mongosh --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name mongo_container
          
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 #fetch-depth is needed for GitVersion
      
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: 5.x
    
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      id: gitversion # step id used as reference for output values
      with:
        useConfigFile: true
        configFilePath: gitversion.yml 
      
    - name: Display GitVersion outputs
      run: |
        echo "Version: ${{ steps.gitversion.outputs.SemVer }}"
        echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: 8.0.x
      
    - name: Prepare package
      run: dotnet nuget add source --username voldovgan2 --password ${{ secrets.PACKAGE_SOURCE_PASSWORD }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/voldovgan2/index.json"
          
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build project 
      run: dotnet build FitnessApp.SettingsApi.sln -c Release --no-restore
    
    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
      env:
        ConnectionString: mongodb://localhost:27017
        DatabaseName: FitnessSettings
        CollecttionName: Settings
      
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        thresholds: '0 100'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push develop
      if: github.ref == 'refs/heads/develop'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile  
        build-args: |
          NUGET_PAT=${{ secrets.PACKAGE_SOURCE_PASSWORD }}
        push: true
        tags: ${{env.API_IMAGE_NAME}}:${{ steps.gitversion.outputs.SemVer }}_alpha
        
    - name: Build and push latest
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile  
        build-args: |
          NUGET_PAT=${{ secrets.PACKAGE_SOURCE_PASSWORD }}
        push: true
        tags: ${{env.API_IMAGE_NAME}}:latest, ${{env.API_IMAGE_NAME}}:${{ steps.gitversion.outputs.SemVer }}
