name: BuildFitnessApp.SettingsApi image

on:
  push:
    branches: [master]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile  
          build-args: |
            NUGET_PAT=${{ secrets.PACKAGE_SOURCE_PASSWORD }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fitness-app:latest
